apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
      version: green
  template:
    metadata:
      labels:
        app: flask
        version: green
    spec:
      containers:
        - name: flask
          image: sha9506/flask-green:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: APP_VERSION
              value: "green"
