apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
      version: blue
  template:
    metadata:
      labels:
        app: flask
        version: blue
    spec:
      containers:
        - name: flask
          image: sha9506/flask-blue:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: APP_VERSION
              value: "blue"
